image: gradle:6.7.1-jdk11

include: '.gitlab-ci-service.yml'


variables:
  ENV: "dev"
  #TASK_CM: "smokeCMTests"
  #TASK_NS: "nsTestsSmoke"
  CYCLE: "latest"
  #SPARK_URL: "https://outlook.office.com/webhook/6371821a-7221-4e98-bfaa-a6f309aa9fe6@8a68f26d-b270-4ef3-ae78-bd695a909445/IncomingWebhook/1bdcdbaeb9c648758f7a9676a239dfb5/d45cc121-c9d1-44d9-893d-51382613cf7a"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - test
  - test_dev
  - test_sit
  - test_prod
  - instrumental
  - pages

.test_run:
  extends: .servisable
  stage: test
  # variables:
  #   TASK: "smoke"
  #   REPORT_URL: "build/reports_ns"
  script:
    - set GROOVY_TURN_OFF_JAVA_WARNINGS=true
    - if [ ! -z ${CM_TEST_BRANCH} ] && git branch -a | egrep "remotes/origin/${CM_TEST_BRANCH}"; then git checkout origin/${CM_TEST_BRANCH}; res=$?; fi
    - if [[ ! -z ${CM_TEST_BRANCH} && $res == 0 ]]; then echo "Running tests from ${CM_TEST_BRANCH} brach"; fi
    - mkdir -p "${REPORT_URL}"
    - chown gradle:gradle ./ -R
    - echo "gradle $TASK -Penv=$ENV -Pci=true -Ptest_cycle=$CYCLE -Ptest_folder=$FOLDER"
    - gradle $TASK -Penv=$ENV -Pci=true -Ptest_cycle=$CYCLE -Ptest_folder=$FOLDER
  after_script:
    - mkdir -p "${REPORT_URL}"
    - cp -TRv build/reports/allure-report/ "${REPORT_URL}/" > /dev/null
  artifacts:
    name: "Report"
    paths:
      - index.html
      - "${REPORT_URL}/"
      - build/allure-results/
    when: always
    reports:
      junit: build/test-results/**/TEST-*.xml
    expire_in: 1 week
  allow_failure: false

test_ns_auto:
  extends: .test_run
  rules:
    - if: $TASK_NS
      when: delayed
      start_in: 5 minutes
  variables:
    TASK: $TASK_NS
    REPORT_URL: "build/reports_ns"
    HISTORY_URL: "history_ns"

test_cm_auto:
  extends: .test_run
  rules:
    - if: $TASK_CM
      when: delayed
      start_in: 5 minutes
  variables:
    TASK: $TASK_CM
    REPORT_URL: "build/reports_cm"
    HISTORY_URL: "history_cm"

test_e2e_auto:
  extends: .test_run
  rules:
    - if: $TASK_NS || $TASK_CM
      when: manual
    - when: never
  variables:
    TASK: "e2eTests"
    REPORT_URL: "build/reports_e2e"
    HISTORY_URL: "history_e2e"
  allow_failure: true

test_e2e_ui_auto:
  extends: .test_run
  rules:
    - if: $TASK_NS || $TASK_CM
      when: manual
    - when: never
  variables:
    TASK: "e2eTestsUI"
    REPORT_URL: "build/reports_e2e"
    HISTORY_URL: "history_e2e"
  allow_failure: true

#dev operations
test_ns_smoke_dev:
  extends: .test_run
  stage: test_dev
  variables:
    ENV: "dev"
    TASK: "nsTestsSmoke"
    REPORT_URL: "build/reports_ns"
    HISTORY_URL: "history_ns"
  rules:
    - if: '$TASK_NS == null && $TASK_CM == null'
      when: manual
    - when: never
  allow_failure: true

test_cm_smoke_dev:
  extends: .test_run
  stage: test_dev
  variables:
    ENV: "dev"
    TASK: "smokeCMTests"
    REPORT_URL: "build/reports_cm"
    HISTORY_URL: "history_cm"
  rules:
    - if: '$TASK_NS == null && $TASK_CM == null'
      when: manual
    - when: never
  allow_failure: true

test_ns_regression_dev:
  extends: .test_run
  stage: test_dev
  variables:
    ENV: "dev"
    TASK: "nsTestRegression"
    REPORT_URL: "build/reports_ns"
    HISTORY_URL: "history_ns"
  rules:
    - if: '$TASK_NS == null && $TASK_CM == null'
      when: manual
    - when: never
  allow_failure: true

test_cm_regression_dev:
  extends: .test_run
  stage: test_dev
  variables:
    ENV: "dev"
    TASK: "devTests"
    REPORT_URL: "build/reports_cm"
    HISTORY_URL: "history_cm"
  rules:
    - if: '$TASK_NS == null && $TASK_CM == null'
      when: manual
    - when: never
  allow_failure: true

test_e2e_dev:
  extends: .test_run
  stage: test_dev
  variables:
    ENV: "dev"
    TASK: "e2eTests"
    REPORT_URL: "build/reports_e2e"
    HISTORY_URL: "history_e2e"
  rules:
    - if: '$TASK_NS == null && $TASK_CM == null'
      when: manual
    - when: never
  allow_failure: true

test_ui_dev:
  extends: .test_run
  stage: test_dev
  variables:
    ENV: "dev"
    TASK: "uiTests"
    REPORT_URL: "build/reports_cm"
    HISTORY_URL: "history_cm"
  rules:
    - if: '$TASK_NS == null && $TASK_CM == null'
      when: manual
    - when: never
  allow_failure: true

#sit operations
test_ns_smoke_sit:
  extends: .test_run
  stage: test_sit
  variables:
    ENV: "sit"
    TASK: "nsTestsSmoke"
    REPORT_URL: "build/reports_ns"
    HISTORY_URL: "history_ns"
  rules:
    - if: '$TASK_NS == null && $TASK_CM == null'
      when: manual
    - when: never
  allow_failure: true

test_cm_smoke_sit:
  extends: .test_run
  stage: test_sit
  variables:
    ENV: "sit"
    TASK: "smokeCMTests"
    REPORT_URL: "build/reports_cm"
    HISTORY_URL: "history_cm"
  rules:
    - if: '$TASK_NS == null && $TASK_CM == null'
      when: manual
    - when: never
  allow_failure: true

test_ns_regression_sit:
  extends: .test_run
  stage: test_sit
  variables:
    ENV: "sit"
    TASK: "nsTestRegression"
    REPORT_URL: "build/reports_ns"
    HISTORY_URL: "history_ns"
  rules:
    - if: '$TASK_NS == null && $TASK_CM == null'
      when: manual
    - when: never
  allow_failure: true

test_cm_regression_sit:
  extends: .test_run
  stage: test_sit
  variables:
    ENV: "sit"
    TASK: "sitTests"
    REPORT_URL: "build/reports_cm"
    HISTORY_URL: "history_cm"
  rules:
    - if: '$TASK_NS == null && $TASK_CM == null'
      when: manual
    - when: never
  allow_failure: true

test_e2e_sit:
  extends: .test_run
  stage: test_sit
  variables:
    ENV: "sit"
    TASK: "e2eTests"
    REPORT_URL: "build/reports_e2e"
    HISTORY_URL: "history_e2e"
  rules:
    - if: '$TASK_NS == null && $TASK_CM == null'
      when: manual
    - when: never
  allow_failure: true

test_e2e_ui_sit:
  extends: .test_run
  stage: test_sit
  variables:
    ENV: "sit"
    TASK: "e2eTestsUI"
    REPORT_URL: "build/reports_e2e"
    HISTORY_URL: "history_e2e"
  rules:
    - if: '$TASK_NS == null && $TASK_CM == null'
      when: manual
    - when: never
  allow_failure: true

test_mp_contract_sit:
  extends: .test_run
  stage: test_sit
  variables:
    ENV: "sit"
    TASK: "e2eTestsUiContract"
    REPORT_URL: "build/reports_e2e"
    HISTORY_URL: "history_e2e"
  rules:
    - if: '$TASK_NS == null && $TASK_CM == null'
      when: manual
    - when: never
  allow_failure: true

test_ns_prod:
  extends: .test_run
  stage: test_prod
  variables:
    ENV: "prod"
    TASK: "nsTestProd"
    REPORT_URL: "build/reports_ns"
    HISTORY_URL: "history_ns"
  rules:
    - if: '$TASK_NS == null && $TASK_CM == null'
      when: manual
    - when: never
  allow_failure: true

test_cm_prod:
  extends: .test_run
  stage: test_prod
  variables:
    ENV: "prod"
    TASK: "prodTests"
    REPORT_URL: "build/reports_cm"
    HISTORY_URL: "history_cm"
  rules:
    - if: '$TASK_NS == null && $TASK_CM == null'
      when: manual
    - when: never
  allow_failure: true

test_e2e_prod:
  extends: .test_run
  stage: test_prod
  variables:
    ENV: "prod"
    TASK: "e2eProdTests"
    REPORT_URL: "build/reports_e2e"
    HISTORY_URL: "history_e2e"
  rules:
    - if: '$TASK_NS == null && $TASK_CM == null'
      when: manual
    - when: never
  allow_failure: true

#Instruments
zephyr_link:
  stage: instrumental
  script:
    - chown gradle:gradle ./ -R
    - gradle zephyrLinkTaskNS -Penv=$ENV -Dtest_cycle=$CYCLE -Ptest_cycle=$CYCLE -Ptest_folder=$FOLDER
    - gradle --stop
  when: manual
  allow_failure: true

zephyr_sync:
  stage: instrumental
  script:
    - chown gradle:gradle ./ -R
    - gradle zephyrSyncTaskNS -Penv=$ENV -Dtest_cycle=$CYCLE -Ptest_cycle=$CYCLE -Ptest_folder=$FOLDER
    - gradle --stop
  when: manual
  allow_failure: true


pages:
  stage: pages
  rules:
    - if: $TASK_NS || $TASK_CM
      when: always
    - when: never
  script:
    - echo "Generate page with url ${CI_PAGES_URL}"
    - mkdir .public
    - cp -v index.html .public
    - if [ -d "build/reports_ns" ]; then
    - echo "copy NS report to pages"
    - mkdir -p .public/nsDeployReport
    - cp -TRv build/reports_ns/ .public/nsDeployReport/ > /dev/null
    - fi
    - if [ -d "build/reports_cm" ]; then
    - echo "copy CM report to pages"
    - mkdir -p .public/cmDeployReport
    - cp -TRv build/reports_cm/ .public/cmDeployReport/ > /dev/null
    - fi
    - if [ -d "build/reports_e2e" ]; then
    - echo "copy e2e report to pages"
    - mkdir -p .public/e2eDeployReport
    - cp -TRv build/reports_e2e/ .public/e2eDeployReport/ > /dev/null
    - fi
    - mv .public public
  artifacts:
    paths:
      - public
    expire_in: 5 days
